### ISSUE TITLE
[ANSIBLERUN][FEATURE] - ADD ABILITY FOR GIVING COMPLEX VARS AS B64

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/crossplane#1]
HOW DO WE WANT TO USE THIS FEATURE:

```yaml
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: AnsibleRun
metadata:
  name: baseos-k3s-sprechstunde13
  namespace: crossplane-system
spec:
  pipelineRunName: baseos-k3s-sprechstunde13
  createInventory: "false"
  extraVarsFile: W2luaXRpYWxfbWFzdGVyX25vZGVdCmhvbWVydW4taW50LmxhYnVsLnN2YS5kZQoKW2FkZGl0aW9uYWxfbWFzdGVyX25vZGVzXQpob21lcnVuLWludC0yLmxhYnVsLnN2YS5kZQpob21lcnVuLWludC0zLmxhYnVsLnN2YS5kZQo=
#...
```

EXAMPLE-USECASE:

```yaml
  values_cilium: |
    ---
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    cni:
      chainingMode: "none"

  helmChartConfig:
    cilium:
      name: rke2-cilium
      namespace: kube-system
      release_values: "{{ values_cilium }}"
```
